# Generated by Django 5.2.2 on 2025-06-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainapp',
            name='text',
            field=models.TextField(max_length=250),
        ),
    ]
