# Generated by Django 5.2.2 on 2025-06-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_mainapp_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField()),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('readability_score', models.FloatField(blank=True, null=True)),
                ('keywords', models.JSONField(default=list)),
            ],
        ),
    ]
