# Generated by Django 5.2.2 on 2025-06-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_seoanalysis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seoanalysis',
            old_name='analyzed_at',
            new_name='analyzed_on',
        ),
        migrations.RenameField(
            model_name='seoanalysis',
            old_name='original_text',
            new_name='input_text',
        ),
        migrations.AddField(
            model_name='seoanalysis',
            name='suggestions',
            field=models.TextField(blank=True),
        ),
    ]
